### ISSUE TITLE
The url is 404

### ISSUE THREAD

**Issue by hiyangguo** [typescript-cheatsheets/speed#1]
https://github.com/typescript-cheatsheets/speed#typescript-speed

![image](https://user-images.githubusercontent.com/15609339/117754596-379a0a00-b24d-11eb-8cbf-ce3f5ccdc96f.png)

>  https://github.com/typescript-cheatsheets/react-typescript-cheatsheet/blob/master/ADVANCED.md#typescript-30

This link is not a web page

**Comment by swyxio** [comment]
fixed, ty!
